test_average (__main__.TestExercice) ... ok
test_square (__main__.TestExercice) ... ok
test_square_root (__main__.TestExercice) ... ok
test_to_celsius (__main__.TestExercice) ... ERROR
test_to_degrees (__main__.TestExercice) ... ERROR
test_to_farenheit (__main__.TestExercice) ... ERROR
test_to_radians (__main__.TestExercice) ... FAIL

======================================================================
ERROR: test_to_celsius (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 92, in test_to_celsius
    output = [exercice.to_celsius(v) for v in values]
  File "test_exercice.py", line 92, in <listcomp>
    output = [exercice.to_celsius(v) for v in values]
AttributeError: module 'exercice' has no attribute 'to_celsius'

======================================================================
ERROR: test_to_degrees (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 80, in test_to_degrees
    output = [exercice.to_degrees(v) for v in values]
  File "test_exercice.py", line 80, in <listcomp>
    output = [exercice.to_degrees(v) for v in values]
AttributeError: module 'exercice' has no attribute 'to_degrees'

======================================================================
ERROR: test_to_farenheit (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 104, in test_to_farenheit
    output = [exercice.to_farenheit(v) for v in values]
  File "test_exercice.py", line 104, in <listcomp>
    output = [exercice.to_farenheit(v) for v in values]
AttributeError: module 'exercice' has no attribute 'to_farenheit'

======================================================================
FAIL: test_to_radians (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 64, in test_to_radians
    self.assertListEqual(
AssertionError: Lists differ: [-0.08668468618238356, 0.1759825181059475, 6.283490739798579, 6.997344948274681] != [-0.08668468618238503, 0.17598251810595048, 6.283490739798685, 6.9973449482748]

First differing element 0:
-0.08668468618238356
-0.08668468618238503

- [-0.08668468618238356, 0.1759825181059475, 6.283490739798579, 6.997344948274681]
?                    --                  ^^                 --                - -

+ [-0.08668468618238503, 0.17598251810595048, 6.283490739798685, 6.9973449482748]
?                   ++                  ++ ^                ++
 : Mauvais calcul de degres -> radians

----------------------------------------------------------------------
Ran 7 tests in 0.001s

FAILED (failures=1, errors=3)
